const SEPTEMBER_2026_BUDGET_LINES = [
  ['Household Expenses', [
    ['Protien', 10000, 10000],
    ['Vegitble / Fruits/Groceries (Canteen)', 5000, 5000],
    ['Milk', 0, 0],
    ['House Rent', 21000, 21000],
    ['Repair / Maintainance / Parking', 0, 0],
    ['Conveyance (Petrol/ Disel/ Cab / Bus)', 2500, 2500],
    ['Gas / LPG / MNGL', 200, 200],
    ['Medicine (All family)', 500, 500],
    ['Electricity', 3000, 3000],
    ['Mobile / Wifi / Gadgets', 3900, 3900],
    ['Newspaper', 0, 0],
    ['Maid / Laundry / Driver', 3500, 3500],
    ['Other (Specify)', 0, 0],
  ]],
  ['Lifestyle', [
    ['Cloths', 0, 0],
    ['Shoes', 0, 0],
    ['Saloon / Spa', 1000, 6000],
    ['Parlour / Cosmetics', 500, 5000],
    ['Dining Out / Pub', 500, 10000],
    ['Gym / Yoga / Aerobics / Zumba', 0, 0],
    ['Travelling / Trip', 20000, 20000],
    ['Movies / Books', 0, 1000],
    ['Gifts', 5000, 0],
    ['Smoking / Liquor', 0, 0],
    ['Donations', 5000, 0],
    ['Hobbies / Skills / Learnings', 0, 0],
    ['Other (Specify)', 0, 0],
  ]],
  ['Education/Child Care', [
    ['School Fees', 0, 0],
    ['Tution Fees', 0, 0],
    ['Stationary', 0, 0],
    ['Sports / Hobbies', 0, 0],
    ['Toys / Games', 0, 0],
    ['Other (Specify)', 0, 0],
  ]],
  ['LOANS & OTHER DEBTS', [
    ['Home Loan/ EMI', 0, 0],
    ['Personal Loan', 0, 0],
    ['Vehicle Loan', 15460, 15460],
    ['Credit Card', 0, 0],
    ['Education Loan', 18587, 0],
    ['Other (Gold Loan / Morgege Loan)', 0, 0],
  ]],
  ['OTT Subscription', [
    ['Netflix', 0, 162],
    ['Disney Hotstar', 0, 0],
    ['Amazon Prime Video', 0, 0],
    ['Jio Cinema Premium', 0, 0],
    ['Sony LIV', 0, 0],
    ['Claude/ AI/ other', 0, 3200],
    ['Linkedin', 0, 0],
    ['Fly.io', 0, 755],
    ['Naukari', 0, 0],
    ['Spotify', 0, 0],
  ]],
].flatMap(([section, categories]) => categories.flatMap(([category, kunalAmount, poojaAmount], sort_order) => [
  { month: 'September_2026', person: 'Kunal', section, category, kind: 'expense', amount: kunalAmount, sort_order },
  { month: 'September_2026', person: 'Pooja', section, category, kind: 'expense', amount: poojaAmount, sort_order },
]));

const INITIAL_BUDGET_MAPPINGS = [
  { section: 'Household Expenses', budget_category: 'House Rent', transaction_category: 'Rent', kind: 'expense' },
  { section: 'Household Expenses', budget_category: 'Conveyance (Petrol/ Disel/ Cab / Bus)', transaction_category: 'Petrol', kind: 'expense' },
  { section: 'Household Expenses', budget_category: 'Conveyance (Petrol/ Disel/ Cab / Bus)', transaction_category: 'Ola/Uber', kind: 'expense' },
  { section: 'Lifestyle', budget_category: 'Dining Out / Pub', transaction_category: 'Outside Food', kind: 'expense' },
  { section: 'LOANS & OTHER DEBTS', budget_category: 'Vehicle Loan', transaction_category: 'Car downpayment/ emi', kind: 'expense' },
  { section: 'OTT Subscription', budget_category: 'Claude/ AI/ other', transaction_category: 'Subscriptions', kind: 'expense' },
];

module.exports = { SEPTEMBER_2026_BUDGET_LINES, INITIAL_BUDGET_MAPPINGS };
